### ISSUE TITLE
Add valid to Data.Validation.Semigroup

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-validation#14]
Add `valid`, akin to `invalid`. This, because `pure` requires a `Semigroup` instance on the error type.

**Comment by paf31** [comment]
I'm curious why you would use `V` without a `Semigroup`?

**Comment by rightfold** [comment]
`Set.singleton`

**Comment by paf31** [comment]
But then you aren't using the `Applicative` instance, right? So why not use `Either`?

**Comment by rightfold** [comment]
I use `pure` which is in `Applicative`. Similar reasoning: why does `Set.singleton` not have an `Ord` instance?

**Comment by paf31** [comment]
My point is that for `V` to be useful, you need to also be using `<*>` somewhere, which does need `Applicative`.

**Comment by joneshf** [comment]
```PureScript
invalid :: forall a b. a -> V a b
```

There's no constraint on `invalid`, and that's arguably where it would make the most sense.

It seems fine to have:

```PureScript
valid :: forall a b. b -> V a b
```

Put another way, I'm not sure that an argument for _adding_ a `Semigroup` constraint to `invalid` at this point would make much sense.

**Comment by JordanMartinez** [comment]
I think this can be closed now that the constructor has been exported.
