### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-validation#2]
@garyb Any idea why the release versions are still `0.0.*` in this repo? Can I make the next release `0.1.0`?

**Comment by garyb** [comment]
Yep, sounds good. I don't think there's any particular reason for the current version range - I thought we'd bumped everything out of 0.0.x at this point, but I guess this hasn't needed any changes for a long time.

That does make it a breaking change, but apparently nothing depends on it? I thought we used it in `foreign`, or did that not work out in the end?

**Comment by paf31** [comment]
Nope, it became a nightmare so we stuck with `Either` :)
