### ISSUE TITLE
Deprecate (and eventually remove) toEither

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-validation#23]
Now that we expose the `V` constructor and provide a `Newtype` instance, I don't think it makes a lot of sense to provide `toEither` too.

**Comment by thomashoneyman** [comment]
I'm not sure we should deprecate `toEither`; I've used this function a number of times when I want to switch from applicative-style to monadic validation where I need a step to depend on a prior step. I _could_ pattern match or use `unwrap`, but `toEither` is a little clearer (to me, at least). I'm not sure I'd recommend that users of this library change all their uses of `toEither` to be `unwrap` instead.

I don't see any harm in preserving the function in the library for the semantic advantage I see in the name `toEither`, though I agree that in general there's no reason for a library to provide a function like this when `unwrap` will do.

**Comment by JordanMartinez** [comment]
I don't know whether this breakage is worth it. A few thoughts:
- `toEither` is more readable than `un V`
- we don't have a similar `toX` pattern elsewhere AFAIK for `newtype Y = Y X` like situations

**Comment by hdgarrood** [comment]
I think you have to be really careful with “X is more readable than Y” style statements, because these things are _highly_ personal and contextual. I think if this function is being used in a situation where it’s obvious that an Either is being returned but it’s not obvious what type of thing is being converted to Either, then `un V` is more helpful. If the reader doesn’t know what `V` is, that does at least let them know what they need to look up.

**Comment by hdgarrood** [comment]
I’m happy to drop this though, on reflection I agree that it’s probably not quite a good enough reason to break things.

**Comment by JordanMartinez** [comment]
> these things are highly personal and contextual.

Good point. `un V` definitely could be more readable in some contexts.

> on reflection I agree that it’s probably not quite a good enough reason to break things.

Yeah... It's somewhat ironic that I don't think this change is worth breaking over but I think `Effect.Class` is worth breaking because it annoys me to have to use another import that should basically be from `Effect`. I'm not being consistent.

**Comment by JordanMartinez** [comment]
If you're not against this, how about we close the issue?

**Comment by hdgarrood** [comment]
@kl0tl as the person who created the PR, do you have any thoughts?

**Comment by kl0tl** [comment]
I’m fine with keeping toEither, let’s close this!
