### ISSUE TITLE
Validation eliminator

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-validation#32]
Is there a reason for having `unV` instead of a `validation` eliminator, like `maybe` or `either`? If not, should we deprecate `unV` in favor of such eliminator?

**Comment by JordanMartinez** [comment]
I think a `validation` eliminator makes sense. Maybe wait to deprecate the `unV` until next breaking changes release?

**Comment by hdgarrood** [comment]
Is there a problem with having both?

**Comment by kl0tl** [comment]
I don’t like that `unV` reads almost like `un V` while both functions have different types. I suspect it might be confusing to beginners but I’m not sure it’s enough for deprecating `unV` though.

**Comment by hdgarrood** [comment]
Oh, sorry, yes. I forgot that `unV` is already an eliminator. So is the proposal essentially just "rename `unV` to `validation`"?

**Comment by kl0tl** [comment]
I’d like to guide users toward the new eliminator with a warning but otherwise yes, the proposal is essentially renaming `unV` to `validation` (to avoid confusion with `un V` and for consistency with `either` and `maybe`).

**Comment by JordanMartinez** [comment]
We're not going to deprecate `unV` first?

**Comment by thomashoneyman** [comment]
Closed in #33 .
